name: DevFest-ML
channels:
- conda-forge
dependencies:
- python==3.8
- numpy==1.19.2
- pandas==1.1.2
- matplotlib==3.3.2
- scikit-learn==0.23.2
- notebook==6.1.4
- xlrd
- fastapi==0.61.1
- uvicorn==0.12.1
